name: YFP APK Olustur

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depodaki dosyalari indir
        uses: actions/checkout@v4

      - name: Flutter kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter projesi olustur
        run: flutter create yfp_app

      - name: YFP ana ekranini kopyala
        run: cp lib/main.dart yfp_app/lib/main.dart

      - name: Kalici kayit paketini ekle
        working-directory: yfp_app
        run: flutter pub add shared_preferences
        
      - name: Paketleri indir
        working-directory: yfp_app
        run: flutter pub get

      - name: APK olustur
        working-directory: yfp_app
        run: flutter build apk --debug

      - name: APK kaydet
        uses: actions/upload-artifact@v4
        with:
          name: YFP-APK
          path: yfp_app/build/app/outputs/flutter-apk/app-debug.apk
